name: Autograding Tests
on:  
  workflow_dispatch: 
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  simply-wf-file-check:
    if: github.actor != 'github-classroom[bot]'        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if custom YAML file exists
        run: |
          if [[ ! -f .github/workflows/expressions.yaml ]]; then
            echo "Error: expressions.yaml is missing!"
            exit 1
          fi
          echo "expressions.yaml file exists."

      - name: Check for expected workflow triggers
        run: |
          if ! grep -q "workflow_dispatch" .github/workflows/expressions.yaml; then
            echo "Error: 'workflow_dispatch' trigger is missing!"
            exit 1
          fi
          if ! grep -q "pull_request" .github/workflows/expressions.yaml; then
            echo "Error: 'pull_request' trigger is missing!"
            exit 1
          fi
          echo "Both triggers are present."

      - name: Verify jobs in the YAML file
        run: |
          grep -q "debug-check" .github/workflows/expressions.yaml || (echo "Missing job: debug-check" && exit 1)
          grep -q "functions-pr-data" .github/workflows/expressions.yaml || (echo "Missing job: functions-pr-data" && exit 1)
          echo "All required jobs are present."

      - name: Verify steps in 'debug-check' job
        run: |
          grep -q "\[Debug\] Print Debug Info" .github/workflows/expressions.yaml || (echo "Missing step: Print Debug Info" && exit 1)
          grep -q "\[Debug\] Triggered from Main" .github/workflows/expressions.yaml || (echo "Missing step: Triggered from Main" && exit 1)
          echo "Steps in 'debug-check' verified."

      - name: Verify steps in 'functions-pr-data' job
        run: |
          grep -q "Print PR Info" .github/workflows/expressions.yaml || (echo "Missing step: Print PR Info" && exit 1)
          grep -q "Bug Check" .github/workflows/expressions.yaml || (echo "Missing step: Bug Check" && exit 1)
          grep -q "Sleep and Cancel" .github/workflows/expressions.yaml || (echo "Missing step: Sleep and Cancel" && exit 1)
          echo "Steps in 'functions-pr-data' verified."

      - name: Check for valid input definitions in workflow_dispatch
        run: |
          grep -q "inputs:" .github/workflows/expressions.yaml || (echo "Missing 'inputs' section!" && exit 1)
          grep -q "debug:" .github/workflows/expressions.yaml || (echo "Missing 'debug' input!" && exit 1)
          grep -q "fail:" .github/workflows/expressions.yaml || (echo "Missing 'fail' input!" && exit 1)
          echo "Inputs section verified."
